export const enum Cmd {
  ON_OFF = '0<2',
  VOLUME_UP = '0<3',
  VOLUME_DOWN = '0<4',
  MUTE = '0<5',
  LOUDNESS = '0;>',
  INPUT_AM = '0<9',
  INPUT_FM = '0<<',
  INPUT_CD = '0<>',
  INPUT_PHONO = '0<=',
  INPUT_TV = '0<;',
  INPUT_TAPE_1 = '09?',
  INPUT_TAPE_2 = '09@',
  STOP = '0:4',
  PAUSE = '0:5',
  START = '0:6',
  FAST_FORWARD = '0:2',
  REWIND = '0:3',
  XMIT_STAT = '0:7'
}
